### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by jln-pl** [msn0/sweter#12]
I got this message after running "sweter" command. You forgot about "Promise" module.

``` javascript
/workspace/sweter/lib/runner/phantomas.js:12
  return new Promise(promiseRun.bind(this, url, options));
             ^
ReferenceError: Promise is not defined
    at Object.module.exports.run (/workspace/sweter/lib/runner/phantomas.js:12:14)
    at Object.module.exports.run (/workspace/sweter/index.js:71:6)
    at Object.<anonymous> (/workspace/sweter/cli.js:62:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by msn0** [comment]
Sweter uses native promises. Please upgrade your nodejs version to 0.12.
